apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: adventurelog-db
spec:
  instances: 1

  storage:
    size: 5Gi

  monitoring:
    enablePodMonitor: true

  imageName: ghcr.io/cloudnative-pg/postgis:16-3.5

  bootstrap:
    initdb:
      postInitTemplateSQL:
        - CREATE EXTENSION postgis;
        - CREATE EXTENSION postgis_topology;
        - CREATE EXTENSION fuzzystrmatch;
        - CREATE EXTENSION postgis_tiger_geocoder;
