apiVersion: v1
kind: Service
metadata:
  name: adventurelog

spec:
  selector:
    app: adventurelog

  ports:
  - protocol: TCP
    port: 8000
    targetPort: api
    name: api
  - protocol: TCP
    port: 80
    targetPort: frontend
    name: frontend
