apiVersion: v1
kind: ConfigMap
metadata:
  name: adguard-backup-scripts

data:
  backup_script.sh: |
    #!/usr/bin/env bash
    set -euo pipefail

    backup_file=$(date "+%Y%m%d-%H%M").tgz
    kubectl cp dns/adguard-0:/opt/adguardhome/work work/
    kubectl cp dns/adguard-0:/opt/adguardhome/conf conf/
    tar czf $backup_file work/ conf/

    mc mv $backup_file cluster/backups/adguard/$backup_file
