apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config

data:
  bookmarks.yaml: ""

  custom.css: ""

  custom.js: ""

  docker.yaml: ""

  kubernetes.yaml: |
    mode: cluster

  services.yaml: ""

  settings.yaml: ""

  widgets.yaml: |
    # https://gethomepage.dev/widgets/info/kubernetes/
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: false
          cpu: true
          memory: true
          showLabel: true
