# Source: https://github.com/prometheus-operator/kube-prometheus/blob/main/manifests/prometheusAdapter-apiService.yaml
apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  labels:
    app.kubernetes.io/name: metrics-adapter
  name: v1beta1.metrics.k8s.io

spec:
  group: metrics.k8s.io
  groupPriorityMinimum: 100
  insecureSkipTLSVerify: true
  service:
    name: metrics-adapter
    namespace: monitoring
  version: v1beta1
  versionPriority: 100
