# Source: https://github.com/prometheus-operator/kube-prometheus/blob/main/manifests/prometheusAdapter-roleBindingAuthReader.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/name: metrics-adapter
  name: resource-metrics-auth-reader
  namespace: kube-system

roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: extension-apiserver-authentication-reader

subjects:
- kind: ServiceAccount
  name: metrics-adapter
  namespace: monitoring
