# Source: https://github.com/prometheus-operator/kube-prometheus/blob/main/manifests/prometheusAdapter-serviceAccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: metrics-adapter
  name: metrics-adapter

automountServiceAccountToken: false
