# Source: https://github.com/prometheus-operator/kube-prometheus/blob/main/manifests/prometheusAdapter-serviceMonitor.yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/name: metrics-adapter
  name: metrics-adapter

spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: metrics-adapter

  endpoints:
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    interval: 30s
    metricRelabelings:
    - action: drop
      regex: (apiserver_client_certificate_.*|apiserver_envelope_.*|apiserver_flowcontrol_.*|apiserver_storage_.*|apiserver_webhooks_.*|workqueue_.*)
      sourceLabels:
      - __name__
    port: https
    scheme: https
    tlsConfig:
      insecureSkipVerify: true
