apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner//deploy/?timeout=120&ref=nfs-subdir-external-provisioner-4.0.18
- ./namespace.yaml

patches:
- path: nfs-config-deployment-patch.yaml
- path: storageclass-patch.yaml
