# Source: https://github.com/prometheus-operator/kube-prometheus/blob/main/manifests/nodeExporter-service.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: node-exporter
  name: node-exporter

spec:
  selector:
    app.kubernetes.io/name: node-exporter
  clusterIP: None
  ports:
  - name: https
    port: 9100
    targetPort: https
