# Source: https://github.com/prometheus-operator/kube-prometheus/blob/main/manifests/alertmanager-alertmanager.yaml
apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
  labels:
    app.kubernetes.io/name: alertmanager
  name: main

spec:
  image: quay.io/prometheus/alertmanager:v0.27.0
  nodeSelector:
    kubernetes.io/os: linux
  podMetadata:
    labels:
      app.kubernetes.io/name: alertmanager
    annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/port: '9093'
      prometheus.io/path: '/metrics'
  replicas: 1
  resources:
    limits:
      cpu: 100m
      memory: 100Mi
    requests:
      cpu: 4m
      memory: 100Mi
  secrets: []
  serviceAccountName: alertmanager
  version: 0.27.0
