# Source: https://github.com/prometheus-operator/kube-prometheus/blob/main/manifests/alertmanager-serviceAccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: alertmanager
  name: alertmanager

automountServiceAccountToken: false
