apiVersion: "jdost.us/v1alpha1"
kind: SecretRequest
metadata:
  name: mealie-backup-credentials

spec:
  secrets:
  - name: minio_host
    note: Cluster service address for the minio API (no scheme, e.g. `minio.minio:9001`)
  - name: minio_access_key
    note: Access Key for minio access
  - name: minio_secret_key
    note: Secret Key for minio access
  - name: mealie_api_token
    note: Retreived from mealie, generated at `/user/profile/api-tokens`
