apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: immich-ml
  labels:
    apps.kubernetes.io/name: immich-ml

spec:
  replicas: 1
  selector:
    matchLabels:
      app: immich-ml

  template:
    metadata:
      labels:
        app: immich-ml

    spec:
      containers:
      - name: ml
        image: ghcr.io/immich-app/immich-machine-learning:release
        ports:
        - containerPort: 3003
          name: http
        env:
        - name: IMMICH_PORT
          value: "3003"
        volumeMounts:
        - name: models
          mountPath: /cache

  volumeClaimTemplates:
  - metadata:
      name: models
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
