apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: immich-db

spec:
  instances: 1

  storage:
    size: 10Gi

  monitoring:
    enablePodMonitor: true

  # Use psql 16 w/ pgvectors image (see https://github.com/tensorchord/cloudnative-pgvecto.rs)
  #   psql-17 images only come with 0.4.0 of the library, which immich doesn't support
  #imageName: ghcr.io/tensorchord/cloudnative-pgvecto.rs:17.2
  imageName: ghcr.io/tensorchord/cloudnative-pgvecto.rs:16-v0.3.0
  postgresql:
    shared_preload_libraries:
      - "vectors.so"
    parameters:
      search_path: '"$user", public, vectors'

  enableSuperuserAccess: true
  bootstrap:
    initdb:
      database: immich
      owner: immich
      postInitApplicationSQL:
        - CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
        - CREATE EXTENSION IF NOT EXISTS cube;
        - CREATE EXTENSION IF NOT EXISTS earthdistance CASCADE;
        - CREATE EXTENSION IF NOT EXISTS vectors;
        - CREATE EXTENSION IF NOT EXISTS pg_trgm;
        - CREATE EXTENSION IF NOT EXISTS unaccent;
        - ALTER DATABASE immich SET search_path TO "$user", public, vectors;
        - GRANT USAGE ON SCHEMA vectors TO immich;
        - GRANT SELECT ON TABLE pg_vector_index_stat to immich;
