apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: immich-db

spec:
  instances: 1

  storage:
    size: 10Gi

  monitoring:
    enablePodMonitor: true

  imageName: ghcr.io/tensorchord/cloudnative-vectorchord:17-0.4.3
  postgresql:
    shared_preload_libraries:
      - "vchord.so"
    parameters:
      search_path: '"$user", public, vectors'

  enableSuperuserAccess: true
  bootstrap:
    initdb:
      database: immich
      owner: immich
      postInitApplicationSQL:
        - CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
        - CREATE EXTENSION IF NOT EXISTS cube;
        - CREATE EXTENSION IF NOT EXISTS earthdistance CASCADE;
        - CREATE EXTENSION IF NOT EXISTS pg_trgm;
        - CREATE EXTENSION IF NOT EXISTS unaccent;
          CREATE EXTENSION IF NOT EXISTS vchord CASCADE;
