---
apiVersion: v1
kind: Service
metadata:
  name: immich

spec:
  selector:
    app: immich-server

  ports:
  - protocol: TCP
    port: 80
    targetPort: http
    name: http
---
apiVersion: v1
kind: Service
metadata:
  name: immich-ml

spec:
  selector:
    app: immich-ml

  ports:
  - protocol: TCP
    port: 80
    targetPort: http
    name: http
