apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: immich
  labels:
    apps.kubernetes.io/name: immich

spec:
  replicas: 1
  selector:
    matchLabels:
      app: immich-server

  template:
    metadata:
      labels:
        app: immich-server
        app.kubernetes.io/name: immich

    spec:
      containers:
      - name: server
        image: ghcr.io/immich-app/immich-server:release
        ports:
        - containerPort: 2283
          name: http
        - containerPort: 8081
          name: api-metrics
        - containerPort: 8082
          name: service-metrics
        env:
        - name: DB_URL
          valueFrom:
            secretKeyRef:
              name: immich-db-app
              key: uri
        - name: DB_VECTOR_EXTENSION
          value: "vectorchord"
        - name: REDIS_HOSTNAME
          value: "redis"
        - name: REDIS_PORT
          value: "6379"
        - name: CPU_CORES
          value: "2"
        - name: IMMICH_PORT
          value: "2283"
        - name: IMMICH_MEDIA_LOCATION
          value: /media
        - name: IMMICH_MACHINE_LEARNING_URL
          value: "http://immich-ml"
        volumeMounts:
        - name: photos
          mountPath: /media
        resources:
          requests:
            cpu: 2.0
            memory: 1Gi
          limits:
            cpu: 4.0
            memory: 4Gi
      volumes:
      - name: photos
        persistentVolumeClaim:
          claimName: photos
