apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: minio-cluster

spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: minio-api

  endpoints:
  - interval: 60s
    path: /minio/v2/metrics/cluster
    honorLabels: true
    port: http
