apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: shiori
  labels:
    app.kubernetes.io/name: shiori

spec:
  replicas: 1
  selector:
    matchLabels:
      app: shiori
  template:
    metadata:
      labels:
        app: shiori
        app.kubernetes.io/name: shiori
    spec:
      containers:
      - name: shiori
        image: ghcr.io/go-shiori/shiori:latest
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: SHIORI_DIR
          value: /srv/shiori
        - name: PG_USER
          valueFrom:
            secretKeyRef:
              name: shiori-db-app
              key: user
        - name: PG_PASSWORD
          valueFrom:
            secretKeyRef:
              name: shiori-db-app
              key: password
        - name: PG_HOST
          valueFrom:
            secretKeyRef:
              name: shiori-db-app
              key: host
        - name: PG_PORT
          valueFrom:
            secretKeyRef:
              name: shiori-db-app
              key: port
        - name: PG_DBNAME
          valueFrom:
            secretKeyRef:
              name: shiori-db-app
              key: dbname
        - name: SHIORI_DATABASE_URL
          value: "postgres://$(PG_USER):$(PG_PASSWORD)@$(PG_HOST):$(PG_PORT)/$(PG_DBNAME)"
        envFrom:
        - secretRef:
            name: shiori-config
        volumeMounts:
        - name: shiori-data
          mountPath: /srv/shiori
  volumeClaimTemplates:
  - metadata:
      name: shiori-data
    spec:
       accessModes:
       - ReadWriteOnce
       resources:
         requests:
           storage: 5Gi
