apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: alertmanager

spec:
  instanceSelector:
    matchLabels:
      dashboards: "grafana"
  datasource:
    name: alertmanager
    type: alertmanager
    access: proxy
    url: http://alertmanager-operated:9093
    isDefault: true
    jsonData:
      implementation: prometheus
      handleGrafanaManagedAlerts: false
      tlsSkipVerify: true
      timeInterval: "5s"
