apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# I don't know if you can easily change this, I have always stuck with the default
#   namespace
namespace: cert-manager

resources:
- https://github.com/cert-manager/cert-manager/releases/download/v1.16.1/cert-manager.yaml
- ./clusterissuer.yaml
- ./secrets.yaml
