apiVersion: apps/v1
kind: Deployment
metadata:
  name: cert-manager

spec:
  template:
    spec:
      containers:
      - name: cert-manager-controller
        args:
        - --v=2
        - --cluster-resource-namespace=$(POD_NAMESPACE)
        - --leader-election-namespace=kube-system
        - --acme-http01-solver-image=quay.io/jetstack/cert-manager-acmesolver:v1.16.2
        - --max-concurrent-challenges=60
        # These are the added flags, pointing to the cloudflare DNS server here
        - --dns01-recursive-nameservers-only
        - --dns01-recursive-nameservers=1.1.1.1:53
