apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: homepage

spec:
  rules:
  - host: home
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: homepage
              port:
                name: http
