apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns

spec:
  template:
    spec:
      containers:
      - name: external-dns
        args:
        - --source=ingress
        - --source=service
        - --provider=webhook
      - name: adguard-webhook
        image: ghcr.io/muhlba91/external-dns-provider-adguard:latest
        ports:
          - containerPort: 8888
            name: http
          - containerPort: 8080
            name: healthz
        livenessProbe:
          httpGet:
            path: /healthz
            port: healthz
          initialDelaySeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /healthz
            port: healthz
          initialDelaySeconds: 10
          timeoutSeconds: 5
        env:
          - name: LOG_LEVEL
            value: debug
          - name: ADGUARD_URL
            value: http://adguard
          - name: DRY_RUN
            value: "false"
        envFrom:
        - secretRef:
            name: adguard-provider-credentials
