apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: memos
  labels:
    apps.kubernetes.io/name: memos

spec:
  replicas: 1
  selector:
    matchLabels:
      app: memos

  template:
    metadata:
      labels:
        app: memos
        app.kubernetes.io/name: memos

    spec:
      containers:
      - name: memos
        image: neosmemo/memos:latest
        ports:
        - containerPort: 5230
          name: http
        env:
        - name: MEMOS_PORT
          value: "5230"
        - name: MEMOS_DRIVER
          value: postgres
        - name: MEMOS_DSN
          valueFrom:
            secretKeyRef:
              name: memos-db-app
              key: uri
        volumeMounts:
        - name: memos-data
          mountPath: "/var/opt/memos"

  volumeClaimTemplates:
  - metadata:
      name: memos-data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 5Gi
