apiVersion: apps/v1
kind: Deployment
metadata:
  name: homepage

spec:
  template:
    spec:
      containers:
      - name: homepage
        envFrom:
        - secretRef:
            name: homepage-secrets
