apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: cadvisor

spec:
  template:
    spec:
      containers:
      - name: cadvisor
        args:
          - --housekeeping_interval=10s
          - --max_housekeeping_interval=15s
          - --event_storage_event_limit=default=0
          - --event_storage_age_limit=default=0
          - --enable_metrics=app,cpu,disk,diskIO,memory,network,process
          - --docker_only
          - --store_container_labels=false
          - --whitelisted_container_labels=io.kubernetes.container.name, io.kubernetes.pod.name,io.kubernetes.pod.namespace
