apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ./daemonset.yaml
- ./service.yaml
- ./serviceaccount.yaml
- ./servicemonitor.yaml

patches:
- path: ./daemonset-args.patch.yaml
