apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: cadvisor
  name: cadvisor

spec:
  selector:
    app.kubernetes.io/name: cadvisor
  clusterIP: None
  ports:
  - name: http
    port: 8080
    targetPort: http
