apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana
  labels:
    dashboards: "grafana"

spec:
  deployment:
    spec:
      template:
        metadata:
          labels:
            app.kubernetes.io/name: grafana
        spec:
          containers:
          - name: grafana
            env:
            - name: GF_SECURITY_ADMIN_USER
              valueFrom:
                secretKeyRef:
                  key: username
                  name: grafana-config
            - name: GF_SECURITY_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: grafana-config
            - name: GF_ANALYTICS_ENABLED
              value: "false"
            - name: GF_ANALYTICS_REPORTING_ENABLED
              value: "false"
            - name: WATCH_NAMESPACE
              value: ""
