apiVersion: v1
kind: ConfigMap
metadata:
  name: loki

data:
  loki.yaml: |-
    auth_enabled: false
    compactor:
      working_directory: /tmp/loki/compactor
      compaction_interval: 5m
    ingester:
      chunk_block_size: 262144
      chunk_idle_period: 3m
      chunk_retain_period: 1m
      lifecycler:
        ring:
          replication_factor: 1
      wal:
        dir: /data/loki/wal
    limits_config:
      max_entries_limit_per_query: 5000
      reject_old_samples: true
      reject_old_samples_max_age: 168h
      volume_enabled: true
    memberlist:
      join_members:
      - 'loki-memberlist'
    schema_config:
      configs:
      - from: "2023-01-05"
        index:
          period: 24h
          prefix: index_
        object_store: filesystem
        schema: v13
        store: tsdb
    server:
      grpc_listen_port: 9095
      http_listen_port: 3100
    storage_config:
      tsdb_shipper:
        active_index_directory: /data/tsdb-index
        cache_location: /data/tsdb-cache
      filesystem:
        directory: /data/loki/chunks
    table_manager:
      retention_deletes_enabled: false
      retention_period: 0s
