---
apiVersion: v1
kind: Service
metadata:
  name: loki
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: http-metrics

spec:
  type: ClusterIP
  selector:
    app: loki
  ports:
  - name: http-metrics
    port: 3100
    protocol: TCP
    targetPort: http-metrics
---
apiVersion: v1
kind: Service
metadata:
  name: loki-headless
spec:
  clusterIP: None
  selector:
    app: loki
  ports:
  - name: http-metrics
    port: 3100
    protocol: TCP
    targetPort: http-metrics
---
apiVersion: v1
kind: Service
metadata:
  name: loki-memberlist
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: loki
  ports:
  - name: http
    port: 7946
    protocol: TCP
    targetPort: memberlist-port
  publishNotReadyAddresses: true
