apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gotify
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: Gotify
    gethomepage.dev/description: Notifications
    gethomepage.dev/icon: "sh-gotify"
    # Remove these widgets if you don't want the homepage widget
    gethomepage.dev/widget.type: "gotify"
    # Update this URL to the service DNS for homepage (i.e. `gotify.<namespace>`
    #   if not in the same namespace as homepage)
    gethomepage.dev/widget.url: "http://gotify"
    # This is so you can pass the API token via a secret, see the `homepage-secrets`
    #   file alongside this
    gethomepage.dev/widget.key: "{{HOMEPAGE_VAR_GOTIFY_KEY}}"

spec:
  rules:
  - host: gotify
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: gotify
              port:
                number: 80
