apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gotify
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: Gotify
    gethomepage.dev/description: Notifications
    gethomepage.dev/group: Services
    # Update the path to your actual ingress path or switch to a public icon repo
    gethomepage.dev/icon: "http://gotify/static/favicon-196x196.png"
    gethomepage.dev/widget.type: "gotify"
    gethomepage.dev/widget.url: "http://gotify.gotify"
    gethomepage.dev/widget.key: "{{HOMEPAGE_VAR_GOTIFY_KEY}}"

spec:
  rules:
  - host: gotify
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: gotify
              port:
                number: 80
