apiVersion: v1
kind: ConfigMap
metadata:
  name: forgejo-config
data:
  #[admin]
  FORGEJO__admin__DEFAULT_EMAIL_NOTIFICATIONS: "disabled" # Default configuration for email notifications for users (user configurable). Options: enabled, onmention, disabled

  #[attachments]
  FORGEJO__attachments__PATH: /data/gitea/attachments

  #[database]
  FORGEJO__database__DB_TYPE: "postgres"
  FORGEJO__database__LOG_SQL: "false"
  FORGEJO__database__SSL_MODE: disable
  FORGEJO__database__CHARSET: utf8

  #[DEFAULT]
  APP_NAME: forgejo
  RUN_MODE: prod
  RUN_USER: git

  #[federation]
  FORGEJO__federation__ENABLED: "false"

  #[indexer]
  FORGEJO__indexer__ISSUE_INDEXER_PATH: /data/gitea/indexers/issues.bleve

  #[log]
  FORGEJO__log__MODE: "console, file"
  FORGEJO__log__LEVEL: Info
  FORGEJO__log__ROOT_PATH: /data/gitea/log

  #[mailer]
  FORGEJO__mailer__ENABLED: "true"
  FORGEJO__mailer__PROTOCOL: "dummy"
  FORGEJO__mailer__FROM: "forgejo@localhost"

  #[oauth2]
  FORGEJO__oauth2__ENABLED: "true"

  #[openid]
  FORGEJO__openid__ENABLE_OPENID: "false"
  FORGEJO__openid__ENABLE_OPENID_SIGNIN: "true"
  FORGEJO__openid__ENABLE_OPENID_SIGNUP: "true"

  #[picture]
  FORGEJO__picture__AVATAR_UPLOAD_PATH: /data/gitea/avatars
  FORGEJO__picture__REPOSITORY_AVATAR_UPLOAD_PATH: /data/gitea/repo-avatars
  FORGEJO__picture__DISABLE_GRAVATAR: "true"
  FORGEJO__picture__ENABLE_FEDERATED_AVATAR: "false"
  FORGEJO__picture__AVATAR_MAX_FILE_SIZE: "10485760"

  #[repository]
  FORGEJO__repository__ROOT: /data/git/repositories
  FORGEJO__repository__DEFAULT_PRIVATE: last
  FORGEJO__repository__LOCAL_COPY_PATH: /data/gitea/tmp/local-repo
  FORGEJO__repository__TEMP_PATH: /data/gitea/uploads

  #[security]
  FORGEJO__security__INSTALL_LOCK: "true"

  #[server]
  FORGEJO__server__DOMAIN: "forgejo"
  FORGEJO__server__SSH_DOMAIN: git
  FORGEJO__server__ROOT_URL: http://forgejo/
  FORGEJO__server__STATIC_URL_PREFIX: ""
  FORGEJO__server__LOCAL_ROOT_URL: http://forgejo/
  FORGEJO__server__HTTP_PORT: "3000"    # HTTP listen port of the server (in the pod)
  FORGEJO__server__SSH_PORT: "22"     # SSH port displayed in clone URL

  #[service]
  FORGEJO__service__DISABLE_REGISTRATION: "false"
  FORGEJO__service__REQUIRE_SIGNIN_VIEW: "false"
  FORGEJO__service__REGISTER_EMAIL_CONFIRM: "false"
  FORGEJO__service__ENABLE_NOTIFY_MAIL: "false"
  FORGEJO__service__EMAIL_DOMAIN_WHITELIST: "*"
  FORGEJO__service__ALLOW_ONLY_EXTERNAL_REGISTRATION: "false"
  FORGEJO__service__ENABLE_BASIC_AUTHENTICATION: "true"
  FORGEJO__service__ENABLE_CAPTCHA: "false"
  FORGEJO__service__DEFAULT_KEEP_EMAIL_PRIVATE: "false"
  FORGEJO__service__DEFAULT_ALLOW_CREATE_ORGANIZATION: "true"
  FORGEJO__service__DEFAULT_ENABLE_TIMETRACKING: "true"

  #[metrics]
  FORGEJO__metrics__ENABLED: "true"

  #[session]
  FORGEJO__session__PROVIDER_CONFIG: /data/gitea/sessions
  FORGEJO__session__PROVIDER: file

  #[webhook]
  FORGEJO__webhook__ALLOWED_HOST_LIST: private,loopback
