---
apiVersion: v1
kind: Service
metadata:
  name: forgejo-ssh
spec:
  selector:
    app: forgejo
  ports:
  - protocol: TCP
    port: 22
    targetPort: 22
    name: ssh
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: forgejo
spec:
  selector:
    app: forgejo
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
    name: http
