---
# Source: https://github.com/prometheus-operator/kube-prometheus/blob/main/manifests/prometheus-roleConfig.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/component: prometheus
  name: prometheus-config

rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
---
# Source: https://github.com/prometheus-operator/kube-prometheus/blob/main/manifests/prometheus-roleBindingConfig.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/component: prometheus
  name: prometheus-config

roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: prometheus-config

subjects:
- kind: ServiceAccount
  name: prometheus
