# Source: https://github.com/prometheus-operator/kube-prometheus/blob/main/manifests/prometheus-serviceAccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus

automountServiceAccountToken: true
