# Source: https://github.com/prometheus-operator/kube-prometheus/blob/main/manifests/prometheus-serviceMonitor.yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus

spec:
  endpoints:
  - interval: 30s
    port: web
  selector:
    matchLabels:
      operated-prometheus: 'true'
