---
# Source: https://github.com/prometheus-operator/kube-prometheus/blob/main/manifests/blackboxExporter-clusterRole.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: blackbox-exporter
  name: blackbox-exporter

rules:
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
---
# Source: https://github.com/prometheus-operator/kube-prometheus/blob/main/manifests/blackboxExporter-clusterRoleBinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: blackbox-exporter
  name: blackbox-exporter

roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: blackbox-exporter

subjects:
- kind: ServiceAccount
  name: blackbox-exporter
