# Source: https://github.com/prometheus-operator/kube-prometheus/blob/main/manifests/blackboxExporter-serviceMonitor.yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/name: blackbox-exporter
  name: blackbox-exporter

spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: blackbox-exporter

  endpoints:
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    interval: 30s
    path: /metrics
    port: https
    scheme: https
    tlsConfig:
      insecureSkipVerify: true
