# Source: https://github.com/prometheus-operator/kube-prometheus/blob/main/manifests/blackboxExporter-serviceAccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: blackbox-exporter
  name: blackbox-exporter

automountServiceAccountToken: false
