apiVersion: "jdost.us/v1alpha1"
kind: SecretRequest
metadata:
  name: homepage-secrets

spec:
  secrets:
  - name: HOMEPAGE_VAR_FORGEJO_KEY
    note: |
      API Token, `User Settings` > `Applications`, under `Select Permissions`, you
      need to give it `Read` under `issue`, `notification`, and `repository`
