apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: forgejo
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: Forgejo
    gethomepage.dev/icon: "sh-forgejo"
    gethomepage.dev/description: Git Server
    # Remove these widgets if you don't want the homepage widget
    gethomepage.dev/widget.type: "gitea"
    # Update this URL to the service DNS for homepage (i.e. `forgejo.<namespace>`
    #   if not in the same namespace as homepage)
    gethomepage.dev/widget.url: "http://forgejo/"
    # This is so you can pass the API token via a secret, see the `homepage-secrets`
    #   file alongside this
    gethomepage.dev/widget.key: "{{HOMEPAGE_VAR_FORGEJO_KEY}}"

spec:
  rules:
  - host: git
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: forgejo
              port:
                name: http
  - host: forgejo
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: forgejo
              port:
                name: http
