---
apiVersion: v1
kind: Service
metadata:
  name: adguard-dns

spec:
  type: LoadBalancer
  selector:
    app: adguard

  ports:
  - protocol: UDP
    port: 53
    targetPort: 53
    name: dns
  - protocol: TCP
    port: 853
    targetPort: 853
    name: dns-tls
---
apiVersion: v1
kind: Service
metadata:
  name: adguard

spec:
  selector:
    app: adguard

  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
    name: http
