apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-server

spec:
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8083"
        prometheus.io/path: "/metrics"
