apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: argocd-application-controller

spec:
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8082"
        prometheus.io/path: "/metrics"
