apiVersion: "jdost.us/v1alpha1"
kind: SecretRequest
metadata:
  name: gotify-config

spec:
  secrets:
  - name: default-username
    note: Username used for default gotify login
  - name: default-password
    note: Password used for default gotify login
  - name: password-strength
    note: bcrypt password strength (higher = better but also slower)
