apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns

spec:
  template:
    spec:
      containers:
      - name: adguard-webhook
        image: ghcr.io/muhlba91/external-dns-provider-adguard:v8.0.0
