apiVersion: "jdost.us/v1alpha1"
kind: SecretRequest
metadata:
  name: forgejo-runner-credentials

spec:
  secrets:
  - name: FORGEJO_HOST
    note: internal http service (probably just 'http://forgejo/')
  - name: FORGEJO_RUNNER_TOKEN
    note: >
      Retrieve the generated token as the admin, go to `/admin/action/runners`,
      click the `Create new runner` button, and copy the registration token there
