apiVersion: apps/v1
kind: Deployment
metadata:
  name: forgejo-runner

spec:
  template:
    spec:
      initContainers:
      - name: dir-setup
        image: code.forgejo.org/forgejo/runner:4.0.1
      containers:
      - name: dockerd
        image: dockerd:27.3.1-dind
      - name: runner
        image: code.forgejo.org/forgejo/runner:4.0.1
