apiVersion: "jdost.us/v1alpha1"
kind: SecretRequest
metadata:
  name: minio-root-credentials
  namespace: default

spec:
  secrets:
  # See: https://min.io/docs/minio/kubernetes/upstream/administration/identity-access-management/minio-user-management.html#minio-root-user
  - name: MINIO_ROOT_USER
    note: Username used for logging into minio as the root user
  - name: MINIO_ROOT_PASSWORD
    note: Password used for logging into minio as the root user
