apiVersion: batch/v1
kind: CronJob
metadata:
  name: gotify-backup
spec:
  # Run every night @ 11:03AM UTC (3:03AM PST)
  schedule: '03 11 * * *'
  jobTemplate:
    spec:
      template:
        spec:
          automountServiceAccountToken: true
          serviceAccountName: gotify-backup
          containers:
          - name: backup
            image: ghcr.io/jdost/homelab-backup:latest
            command:
            - /mnt/scripts/backup_script.sh
            env:
            - name: MINIO_HOST
              valueFrom:
                secretKeyRef:
                  name: gotify-backup-credentials
                  key: minio_host
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: gotify-backup-credentials
                  key: minio_access_key
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: gotify-backup-credentials
                  key: minio_secret_key
            - name: MC_HOST_cluster
              value: "http://$(MINIO_ACCESS_KEY):$(MINIO_SECRET_KEY)@$(MINIO_HOST)"
            envFrom:
            - secretRef:
                name: gotify-db-app
            volumeMounts:
            - mountPath: /mnt/scripts
              name: scripts
          volumes:
          - name: scripts
            configMap:
              name: gotify-backup-scripts
              defaultMode: 0555
          restartPolicy: Never
