---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: forgejo-backup

rules:
- apiGroups: [""]
  resources:
  - pods
  verbs:
  - get
  - list
- apiGroups: [""]
  resources:
  - pods/exec
  - pods/cp
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: forgejo-backup

roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: forgejo-backup

subjects:
- kind: ServiceAccount
  name: forgejo-backup
